import nodemailer from 'nodemailer'
import otpverify from '../model/user.phon.verify.js'
import userModel from '../model/user.model.js'



const otpSend = async (email) => {


    try {
        const otp = Math.floor(100000 + Math.random() * 900000)


        const findUserIdByemail = await userModel.findOne({ email}, { _id: 1, })
        console.log(findUserIdByemail)
                
      await otpverify.deleteMany({ userID: findUserIdByemail._id.toString()})
    


    
        

      const client = nodemailer.createTransport({
  host: process.env.SMTP_HOST || "smtp.gmail.com",
  port: process.env.SMTP_PORT ? parseInt(process.env.SMTP_PORT) : 465,
  secure: true, // Gmail prefers SSL on port 465
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS, // must be APP PASSWORD, not normal Gmail password
  },
});
        console.log(client)



     
        

        const writeMessage = {
            to: email,
            subject: "your send by zoops",
            text: `use ${otp} as OTP  to sign-up  your zoops  account .do not share it with anyone.if not generated by you ,you do not worry your account is still safe `,
            from: process.env.EMAIL_USER
        }
        console.log(writeMessage)
        
        const message = await client.sendMail(writeMessage)
        console.log(message)
         

     
        if (!message) {
            return 'somthing to sanding otp'
        }       


            const newUserOtp = await otpverify.create({ userID: findUserIdByemail._id.toString(), otp })

console.log(newUserOtp)
        if (!newUserOtp) {


            return {
                success: false,
                message: "otp sending error",

            };
        }

        return {
            success: true,
            message: "OTP sent successfully",

        };

    } catch (error) {
        return error

    }

}


export default otpSend










