import nodemailer from 'nodemailer'
import otpverify from '../model/user.phon.verify.js'
import userModel from '../model/user.model.js'



const otpSend = async (email) => {


    try {
        const otp = Math.floor(100000 + Math.random() * 900000)
        const findUserIdByemail = await userModel.findOne({ email }, { _id: 1, })
        // delete old  otp
        await otpverify.deleteMany({ userID: findUserIdByemail._id })

    


        const client = nodemailer.createTransport({
             host: process.env.SMTP_HOST,
  port: parseInt(process.env.SMTP_PORT), 
  secure: parseInt(process.env.SMTP_PORT) === 465, // 
            auth: {
                user: process.env.EMAIL_USER,
                pass: process.env.EMAIL_PASS
            }
        })
        const writeMessage = {
            to: email,
            subject: "your send by zoops",
            text: `use ${otp} as OTP  to sign-up  your zoops  account .do not share it with anyone.if not generated by you ,you do not worry your account is still safe `,
            from: process.env.EMAIL_USER
        }
        const message = await client.sendMail(writeMessage)
        console.log(message)
        if (!message) {
            return 'somthing to sanding otp'
        }

            const newUserOtp = await otpverify.create({ userID: findUserIdByemail._id.toString(), otp })
        if (!newUserOtp) {
            return {
                success: false,
                message: "otp sending error",

            };
        }

        return {
            success: true,
            message: "OTP sent successfully",

        };

    } catch (error) {
        return error

    }

}


export default otpSend

