import nodemailer from 'nodemailer'
import otpverify from '../model/user.phon.verify.js'
import userModel from '../model/user.model.js'



const otpSend = async (email) => {


    try {
        const otp = Math.floor(100000 + Math.random() * 900000)


        const findUserIdByemail = await userModel.findOne({ email}, { _id: 1, })

                
    


    
        

      const client = nodemailer.createTransport({
            host: "smtp-relay.brevo.com", // Brevo's SMTP server
    port: 587, // Recommended port for TLS (or 465 for SSL)
    secure: false, // Use 'true' if port 465, 'false' if port 587 or 2525
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS, // must be APP PASSWORD, not normal Gmail password
  },
});



     
        

        const writeMessage = {
            to: email,
            subject: "your send by zoops",
            text: `use ${otp} as OTP  to sign-up  your zoops  account .do not share it with anyone.if not generated by you ,you do not worry your account is still safe `,
            from: process.env.EMAIL_USER
        }
        
        const message = await client.sendMail(writeMessage)
         

     
        if (!message) {
            return 'somthing to sanding otp'
        }       


            const newUserOtp = await otpverify.create({ userID: findUserIdByemail._id.toString(), otp })

        if (!newUserOtp) {


            return {
                success: false,
                message: "otp sending error",

            };
        }

        return {
            success: true,
            message: "OTP sent successfully",

        };

    } catch (error) {
        return error

    }

}


export default otpSend















